# Generated by Django 2.2.10 on 2020-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200607_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
